name: Giro d’Italia 2022
status: closed
start: 2022-05-06
maxCyclistsInUserTeam: 12
jerseys:
  De Roze Trui: 10
  De Blauwe Trui: 5
scoring:
  - 30
  - 15
  - 12
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4
  - 3
