---
name: Parijs Nice 2022
status: closed
start: 2022-03-06
maxCyclistsInUserTeam: 12
jerseys:
  De Gele Trui: 10
  De Bolletjes Trui: 5
scoring:
  - 30
  - 15
  - 12
  - 9
  - 5
  - 4
  - 3
  - 2
  - 1
