---
name: Giro d’Italia 2023
status: open
maxCyclistsInUserTeam: 8
widgetURL:
jerseys:
  De Roze Trui: 10
  De Blauwe Trui: 5
scoring:
  - 30
  - 15
  - 12
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4
  - 3
finalStandingScoring:
  - 150
  - 75
  - 50
  - 40
  - 35
  - 30
  - 28
  - 26
  - 24
  - 22
