---
name: Lint, deploy, http-request

on: 
  push:
    paths-ignore:
    - '.github'
  pull_request:
    paths-ignore:
    - '.github'

jobs:
  YAMLlint:
    name: 🕵️‍♂️ Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              new-line-at-end-of-file: false
              trailing-spaces: false
              line-length: false
              truthy: false
              comments: false
              
  web-deploy:
    name: 🎉 Deploy
    needs: YAMLlint
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 45.82.191.81
          username: tourpoule-data
          password: ${{ secrets.ftppassword }}
          exclude: |
            /.git*
            .git*/**
            2021/**
            2022/**
            readme.md
          dangerous-clean-slate: true

  http-request:
    name: 🫰 HTTP Request
    needs: web-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP request
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.httprequesturl }}
          method: "GET"
