---
name: Deploy and HTTP request

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  test:
    uses: ./.github/workflows/test.yml
  web-deploy:
    name: 🎉 Deploy
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 45.82.191.81
          username: tourpoule-data
          password: ${{ secrets.ftppassword }}
          local-dir: ./data/
          exclude: |
            2021/**
            2022/**
          dangerous-clean-slate: true

  http-request:
    name: 🫰 HTTP Request
    needs: web-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP request
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.httprequesturl }}
          method: "GET"
